services:
###########################
# Setup the JAVA container
###########################
    linux_java:
        container_name: ${NAME_PROJECT}_java
        restart: always
        build: 
            context: ./.docker/images/linux_java/
            args:
                - VALUE_UBUNTU_VERSION=${VALUE_UBUNTU_VERSION}
                - VALUE_JAVA_VERSION=${VALUE_JAVA_VERSION}
        tty: true
        stdin_open: true
        volumes:
            - ./.dockertmp/log/java/:/var/log/docker/java/:rw
            - ./project:/home/project/:rw
            - ./config/data:/docker-entrypoint-initdata.d:rw
            - ./config/dockercron:/var/docker/cron/dockercron:rw
            - ./.dockertmp/tomcat:/var/docker/tomcat:rw
            - ./.dockertmp/jvm:/jvm:rw
        environment:
            - JAVA_NAME_PROJECT=${NAME_PROJECT}
