#!/bin/bash
### BEGIN INIT INFO
# Provides: startserver
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start nodejs server
### END INIT INFO

DAEMON="/var/docker/gcc/updateProject.sh" #ligne de commande du programme, attention à l'extension .py.
DAEMONUSER="root" #utilisateur du programme
daemon_NAME="startautobash" #Nom du programme (doit être identique à l'exécutable).

d_start () {
    /var/docker/gcc/updateProject.sh start
}
 
case "$1" in
    start)
        d_${1}
        ;;

    *)
        echo "Usage: /etc/init.d/$daemon_NAME {start}"
        exit 1
        ;;
esac
exit 0